[package]
name = "ui"
version = "1.0.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
cards = "1.1.1"
ncurses = { version = "5.73.0", features = ["wide"] }
libthyme = { path = "../libthyme" }
